services:
  andejiazhengkaifa:
    image: andejiazhengkaifa
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3001:3001
    environment:
      - NODE_ENV=production
